server:
  port: 9009

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-timeout: 30000
      auto-commit: false
      pool-name: engine_pool_backend
      minimum-idle: 5
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s

flyway:
  locations: classpath:database

logging:
  config: classpath:logging/logback.xml